name: stripe_android
description: Stripe platform implementation for Android
version: 7.0.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  flutter: 3.24.2
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.stripe
        pluginClass: StripeAndroidPlugin
