name: flutter_stripe_web
description: Stripe sdk for Flutter web platform.
version: 2.0.1
homepage: https://github.com/flutter-stripe/flutter_stripe

environment:
  flutter: 3.24.2
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.0.3
  stripe_platform_interface: ^6.0.0
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebStripe
        fileName: flutter_stripe_web.dart
