name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 7.0.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  flutter: 3.24.2
  sdk: '>=3.0.6 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
    path: ../stripe_android
  stripe_ios:
    path: ../stripe_ios
  stripe_platform_interface:
    path: ../stripe_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
